name: Build DOCs
on:
  push:
    tags:
    - '*'
  workflow_dispatch: {}
jobs:
  build:
    name: build-doc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
          wget https://github.com/hydrogram/hydrogram/raw/013268c/dev_tools/generate_docs_json.py
          pip install httpx==0.27.0 lxml==5.2.2
          python generate_docs_json.py
          make
          rm -rf .github compiler Pyrogram* pyrogram* tests .gitignore COPYING*
          rm -f MANIFEST* Makefile NOTICE README.md
          rm -f pyproject.toml hatch_build.py setup.py
          mv docs/build/html/* .
          rm -rf docs venv __pycache__
          touch .nojekyll
          git checkout --orphan gh-pages
          git config user.email "14043624+delivrance@users.noreply.github.com"
          git config user.name "GitHub Action <Dan>"
          git add . -A
          git commit -m "DocGen: Update documentation"
          git push origin gh-pages --force
