# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    tags:
    - '*'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      env:
        TG_HK_HG_DOCS_JSON_URL: ${{ secrets.TG_HK_HG_DOCS_JSON_URL }}
      run: |
        python -m pip install --upgrade pip
        pip install httpx==0.27.0 lxml==5.2.2
        curl -sL ${TG_HK_HG_DOCS_JSON_URL} | python
        pip install -e '.[dev]'
    - name: Build package
      run: hatch build
    - name: Publish package
      env:
        HATCH_INDEX_USER: __token__
        HATCH_INDEX_AUTH: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        hatch publish
